"""
Policy reason codes for attestation, platform admission, supplier assurance,
and secure operations decisions.

Reason codes are intentionally generic and safe for public portfolio use.
"""

# Generic policy outcome
POLICY_PASS = "POLICY_PASS"
POLICY_FAIL = "POLICY_FAIL"

# Existing attestation checks
UNKNOWN_DEVICE = "UNKNOWN_DEVICE"
INVALID_NONCE = "INVALID_NONCE"
FIRMWARE_HASH_MISMATCH = "FIRMWARE_HASH_MISMATCH"
ROLLBACK_DETECTED = "ROLLBACK_DETECTED"

# Platform component checks
ROOT_OF_TRUST_EVIDENCE_MISSING = "ROOT_OF_TRUST_EVIDENCE_MISSING"
ROOT_OF_TRUST_NOT_TRUSTED = "ROOT_OF_TRUST_NOT_TRUSTED"

PLATFORM_SECURITY_MODULE_MISSING = "PLATFORM_SECURITY_MODULE_MISSING"
PLATFORM_SECURITY_MODULE_NOT_TRUSTED = "PLATFORM_SECURITY_MODULE_NOT_TRUSTED"

MANAGEMENT_CONTROLLER_MISSING = "MANAGEMENT_CONTROLLER_MISSING"
MANAGEMENT_CONTROLLER_NOT_TRUSTED = "MANAGEMENT_CONTROLLER_NOT_TRUSTED"
MANAGEMENT_FIRMWARE_MISMATCH = "MANAGEMENT_FIRMWARE_MISMATCH"
MANAGEMENT_INTERFACE_POLICY_FAIL = "MANAGEMENT_INTERFACE_POLICY_FAIL"

NETWORK_DEVICE_MISSING = "NETWORK_DEVICE_MISSING"
NETWORK_DEVICE_NOT_TRUSTED = "NETWORK_DEVICE_NOT_TRUSTED"
NETWORK_FIRMWARE_MISMATCH = "NETWORK_FIRMWARE_MISMATCH"
NETWORK_DEVICE_BLOCKED = "NETWORK_DEVICE_BLOCKED"

HOST_FIRMWARE_MISSING = "HOST_FIRMWARE_MISSING"
HOST_FIRMWARE_NOT_TRUSTED = "HOST_FIRMWARE_NOT_TRUSTED"

# Memory and storage encryption checks
MEMORY_ENCRYPTION_DISABLED = "MEMORY_ENCRYPTION_DISABLED"
STORAGE_ENCRYPTION_DISABLED = "STORAGE_ENCRYPTION_DISABLED"
ENCRYPTION_KEY_UNSEALED = "ENCRYPTION_KEY_UNSEALED"
ENCRYPTION_DOMAIN_NOT_TRUSTED = "ENCRYPTION_DOMAIN_NOT_TRUSTED"

# Supplier / firmware release assurance
SUPPLIER_NOT_APPROVED = "SUPPLIER_NOT_APPROVED"
FIRMWARE_RELEASE_NOT_APPROVED = "FIRMWARE_RELEASE_NOT_APPROVED"
CRITICAL_VULNERABILITY_OPEN = "CRITICAL_VULNERABILITY_OPEN"
SECURITY_REVIEW_INCOMPLETE = "SECURITY_REVIEW_INCOMPLETE"
WAIVER_EXPIRED = "WAIVER_EXPIRED"

# Fleet admission outcome
FLEET_ADMISSION_ALLOWED = "FLEET_ADMISSION_ALLOWED"
FLEET_ADMISSION_DENIED = "FLEET_ADMISSION_DENIED"
PLATFORM_QUARANTINED = "PLATFORM_QUARANTINED"
